### ISSUE TITLE
When using from IPython, total time reported at the end accumulates.

### ISSUE THREAD

**Issue by elpres** [bos/statprof.py#13]
If I profile a script such as this one:

    def main():
        # do something
    
    if __name__ == '__main__':
        import statprof
        statprof.start()
        try:
            main()
        finally:
            statprof.stop()
            statprof.display()

and call it from IPython by repeatedly executing `run script.py`, the total time grows each time by duration of the execution (e.g. 1s, 2s, 3s, ...).

Without looking very deeply into the code, the function `clock()` gets its time from `os.times()`. I am not certain what the values in the list returned by it represent, but the result of `clock()` seems to be the same as what `time.clock()`, which is the CPU time since the module has been imported and that matches well with the observed behavior. Maybe it would be better to use `time.time()` (which returns an absolute time value), then save the current time at `statprof.start()`, and calc the difference by `time.time() - starttime`?

Also, I've noticed this today, but I've been doing the same thing a couple of days ago and was getting more or less constant values for each run. But I can't remember whether I've been working from inside IPython or calling the script directly from the shell. So I'm not sure it really is well reproducible.

**Comment by durin42** [comment]
Is this still an issue?

**Comment by elpres** [comment]
Yes, it is. Here's a test:

1. Save this code as `test.py`:

  ```python
  import statprof

  def fib(n):
      if n < 2:
          return 1
      else:
          return fib(n - 1) + fib(n - 2)

  with statprof.profile():
      fib(35)
  ```

2. From ipython, call `run test.py` several times.
